export const internships = [
  {
    ncics: {
      name: "North Carolina Institute for Climate Studies",
      duration: "3 mon",
      position: "Software Engineer Intern",
      status: "green",
      image: "/images/ncics.jpg",
      linkedin: "https://www.linkedin.com/company/cooperative-institute-for-climate-and-satellites---north-carolina/mycompany/",
      tech: ["NextJS", "AWS", "Docker", "Pulumi"],
      projects: ["Sea Surface Temperature"],
    },
    iitgn: {
      name: "IIT Gandhinagar",
      duration: "15 mon",
      position: "Software Engineer Intern",
      status: "green",
      image: "/images/iitgn.png",
      linkedin: "https://www.linkedin.com/school/indian-institute-of-technology-gandhinagar-iitgn-/mycompany/",
      tech: ["ReactJS", "Docker", "Flask", "AWS S3", "AWS EC2", "NLP", "LID", "Code-Mixed"],
      projects: ["Commentator", "GA"],
    },
    oracle: {
      name: "Oracle",
      duration: "2 mon",
      position: "Software Engineer Intern",
      status: "green",
      image: "/images/oracle.png",
      linkedin: "https://www.linkedin.com/company/oracle/",
      tech: ["Java", "J2EE", "Docker", "Kubernetes", "Java REST", "CRUD", "Postman", "Eclipse", "JAR"],
      projects: ["Flexcube"],
    },
    phionike: {
      name: "Phionike Studio",
      duration: "3 mon",
      position: "Web Development Intern",
      status: "green",
      image: "/images/phionike.png",
      linkedin: "https://www.linkedin.com/company/phionike-solutions/",
      tech: [
        "ReactJS",
        "React Native",
        "Custom npm library",
        "Styled Components",
        "Aframe.io",
      ],
      projects: ["Supersnap", "Web Components Phionike"],
    },
    sapio: {
      name: "Sapio Analytica",
      duration: "3 mon",
      position: "Web Development Intern",
      status: "green",
      image: "/images/sapio.png",
      linkedin: "https://www.linkedin.com/company/sapio-analytics/",
      tech: ["ReactJS", "Context Hook", "CSS", "Styled Components"],
      projects: ["Data Uploading Portal", "Chatbot"],
    },
  },
];
