export const internships = [
  {
    phionike: {
      name: "Phionike Studio",
      duration: "3 mon",
      position: "Tech & Research Intern",
      status: "green",
      image: "/images/phionike.png",
      linkedin: "https://www.linkedin.com/company/phionike-solutions/",
      tech: [
        "ReactJS",
        "React Native",
        "Custom npm library",
        "Styled Components",
        "Aframe.io",
      ],
      projects: ["Supersnap", "Web Components Phionike"],
    },
    sapio: {
      name: "Sapio Analytica",
      duration: "3 mon",
      position: "Front End Developer Intern",
      status: "green",
      image: "/images/sapio.png",
      linkedin: "https://www.linkedin.com/company/sapio-analytics/",
      tech: ["ReactJS", "Context Hook", "CSS", "Styled Components"],
      projects: ["Data Uploading Portal", "Chatbot"],
    },
    dju: {
      name: "DJU External Project",
      duration: "3 mon",
      position: "Front End Developer Intern",
      status: "green",
      image: "/images/unicode.png",
      linkedin: "https://www.linkedin.com/company/djunicode/mycompany/",
      tech: ["ReactJS", "Redux", "CSS", "Styled Components"],
      projects: ["ProShop"],
    },
  },
];
